services:
  db:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - smart-recycle-network
  application:
    container_name: smart-recycle
    ports:
        - "8080:8080"
    depends_on:
      - db
    networks:
      - smart-recycle-network

networks:
  smart-recycle-network:
    driver: bridge