services:
  db:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGODB_URI: ${MONGODB_URI}
    networks:
      - smart-recycle-network
  application:
    container_name: smart-recycle
    ports:
        - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/smart-recycle
      - JSON_WEB_TOKEN_SECRET=sua_chave_secreta
    depends_on:
      - mongodb
    networks:
      - smart-recycle-network

networks:
  smart-recycle-network:
    driver: bridge

